CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uid VARCHAR(255) NOT NULL UNIQUE,
  username VARCHAR(100) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  avatar VARCHAR(255) DEFAULT NULL,
  role VARCHAR(50) DEFAULT 'user',
  balance DECIMAL(10,2) DEFAULT 0.00,
  streak INT DEFAULT 0,
  country VARCHAR(100) DEFAULT NULL,
  lastLogin TIMESTAMP NULL DEFAULT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  offersCompleted INT DEFAULT 0,
  surveysCompleted INT DEFAULT 0,
  refereeName VARCHAR(100) DEFAULT NULL,
  referralEarnings DECIMAL(10,2) DEFAULT 0.00,
  usersInvited INT DEFAULT 0,
  referrer_uid VARCHAR(128) DEFAULT NULL,
  is_private TINYINT(1) DEFAULT 0,
  isBanned TINYINT(1) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS offers (
  id VARCHAR(100) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  reward DECIMAL(10,2) DEFAULT 0.00,
  category VARCHAR(50),
  imageUrl VARCHAR(255),
  difficulty VARCHAR(50),
  isFuture TINYINT(1) DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
