export const GLOBAL_OFFERWALLS = [
  { id: 'cpxresearch', name: 'CPX RESEARCH', logoUrl: 'https://i.ibb.co/1H8s3m8/cpxresearch.png', isHot: true, rating: 4.8, color: '#3b82f6' },
  { id: 'premium', name: 'PREMIUM', logoUrl: 'https://i.ibb.co/27p5gqsQ/IMG-0661.png', isHot: true, rating: 4.8, color: '#ef4444' },
  { id: 'notik', name: 'NOTIK', logoUrl: 'https://i.ibb.co/WwB4CXg/Notik.png', isHot: true, rating: 4.8, color: '#a855f7' },
  { id: 'pubscale', name: 'PUBSCALE', logoUrl: 'https://i.ibb.co/XfZtVX6r/pubscale.png', isHot: true, rating: 4.5, color: '#0ea5e9' },
  { id: 'revtoo', name: 'REVTOO', logoUrl: 'https://i.ibb.co/tFyWGmL/revtoo.png', isHot: false, rating: 4.5, color: '#8b5cf6' },
  { id: 'tplayads', name: 'TPLAYADS', logoUrl: 'https://i.ibb.co/F4RYwt0J/tplayads.png', isHot: false, rating: 4.3, color: '#f97316' },
  { id: 'pixylabs', name: 'PIXYLABS', logoUrl: 'https://i.ibb.co/PGMJvqsN/pixylabs.png', isHot: false, rating: 4.3, color: '#f59e0b' },
  { id: 'cpalead', name: 'CPALEAD', logoUrl: 'https://i.ibb.co/CsJpKK1C/cpalead.png', isHot: true, rating: 4.8, color: '#14b8a6' },
  { id: 'gemiad', name: 'GEMIAD', logoUrl: 'https://i.ibb.co/ZpzgJYxZ/gemiad.png', isHot: false, rating: 4.5, color: '#ec4899' },
  { id: 'mobivortex', name: 'MOBIVORTEX', logoUrl: 'https://i.ibb.co/C3qMjb1q/Mobivortex.png', isHot: false, rating: 4.3, color: '#10b981' },
  { id: 'adlexy', name: 'ADLEXY', logoUrl: 'https://i.ibb.co/vCRTdjQy/adlexy.png', isHot: false, rating: 4.3, color: '#6366f1' },
  { id: 'upwall', name: 'UPWALL', logoUrl: 'https://i.ibb.co/MDXbgywr/upwall.png', isHot: false, rating: 4.3, color: '#06b6d4' },
  { id: 'radientwall', name: 'RADIENTWALL', logoUrl: 'https://i.ibb.co/fdHv9nM7/Radientwall.png', isHot: false, rating: 4.2, color: '#14b8a6' },
  { id: 'offery', name: 'OFFERY', logoUrl: 'https://i.ibb.co/hJgyx5NT/Offery.png', isHot: false, rating: 4.1, color: '#ef4444' },
  { id: 'vortexwall', name: 'VORTEXWALL', logoUrl: 'https://i.ibb.co/HLzhDGVW/Vortexwall.png', isHot: false, rating: 4.0, color: '#3b82f6' },
  { id: 'monlix', name: 'MONLIX', logoUrl: 'https://i.ibb.co/wFXR620x/Notik.png', isHot: false, rating: 4.1, color: '#a855f7' },
  { id: 'ayetstudios', name: 'AYETSTUDIOS', logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=AYET', isHot: false, rating: 4.0, color: '#8b5cf6' },
  { id: 'lootably', name: 'LOOTABLY', logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=LOOT', isHot: false, rating: 4.0, color: '#f97316' },
  { id: 'bitlabs', name: 'BITLABS', logoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=BIT', isHot: false, rating: 4.0, color: '#3b82f6' },
  { id: 'admantum', name: 'ADMANTUM', logoUrl: 'https://i.ibb.co/q3TLgPgJ/admantum.png', isHot: true, rating: 4.9, color: '#ef4444' },
  { id: 'flexwall', name: 'FLEXWALL', logoUrl: 'https://i.ibb.co/0p6dM3gS/flexwall.png', isHot: true, rating: 4.5, color: '#f97316' },
];
